<?php
/**
 * Created by PhpStorm.
 * User : daimajie
 * Email: daimajie@qq.com
 * Date : 2019/1/21
 * Time : 20:16
 */

namespace app\widgets\upload\actions;


use app\components\Helper;
use yii\base\Action;
use Yii;
use yii\base\Exception;
use yii\base\InvalidArgumentException;
use yii\web\Response;
use app\widgets\upload\models\ImageForm;
use yii\web\UploadedFile;
use yii\imagine\Image;

class UploadAction extends Action
{
    public $name;
    public $subDir;
    public $thumb = [ //默认剪切尺寸
        'width' => 370,
        'height' => 238
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //矫正数据
        $this->name = is_string($this->name) ? $this->name: 'image';
        $this->subDir = is_string($this->subDir) ? $this->subDir : $this->controller->id;

        if(intval($this->thumb['width'])<=0 || intval($this->thumb['height'])<=0)
            throw new InvalidArgumentException('配置参数错误.');
    }

    public function runWithParams($params)
    {

        Yii::$app->response->format = Response::FORMAT_JSON;

        try{
            //判断是否为表单提交
            if( !Yii::$app->request->isPost )
                throw new Exception('请求方式不被允许。');

            $model = new ImageForm();
            $model->image = UploadedFile::getInstanceByName($this->name);

            //上传图片
            $ret = $model->upload();

            if(!$ret)
                throw new Exception($model->getFirstError('image'));

            //**剪切图片
            $info = $model->thumb($this->subDir, $this->thumb['width'], $this->thumb['height']);

            return [
                'code' => 0,
                'url' => $info['savePath'],
                'msg' => '上传成功。'
            ];


        }catch (Exception $e){
            return [
                'code' => 3,
                'msg' => $e->getMessage()
            ];
        }
    }
}